version: "2.3"

services:
    sippgame-container:
        image: sippgame-dev-image
        privileged: true
        network_mode: bridge
        environment:
          - PREFIX=${PREFIX:-~/.local}
          - CCACHE_DIR=/sippgame/.ccache
          - CORES_DIR=/cores
        volumes:
          - .:/sippgame:rw
        ports:
          - 8080:8080
        working_dir: /sippgame
    sippgame-dev:
        image: sippgame-dev-image
        privileged: true
        tty: true
        network_mode: bridge
        environment:
          - PREFIX=${PREFIX:-~/.local}
          - CCACHE_DIR=/sippgame/.ccache
          - CORES_DIR=/cores
        volumes:
          - .:/sippgame:rw
        ports:
          - 8080:8080
        working_dir: /sippgame
